### ISSUE TITLE
[Bug] Gun Gets Removed if you Press Tab

### ISSUE THREAD

**Issue by ALFAMAS** [dojwun/qb-inventory#10]
Gun Gets Removed From Hand When you press Tab while Weapon in hand

**Comment by dojwun** [comment]
Alright, i will give it a look over, i changed a few things with weapons but i don’t think I finished it so i will just revert it back

**Comment by dojwun** [comment]
Can you send a video, i can replicate it

**Comment by dojwun** [comment]
fixed by you, thank you
