### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by WrecksBG** [dojwun/qb-inventory#13]
Make time durability for all items including weapons (weapon to have usage durability and time durability) and make it when i double click on item to use

**Comment by dojwun** [comment]
yeah time durability is something i would like to implement, but the item double click should work to use

**Comment by WrecksBG** [comment]
And if you make crafting table to be like in nopixel will be perfect ;)

**Comment by dojwun** [comment]
would you be able to send a video of how it functions... or a pic please

**Comment by WrecksBG** [comment]
https://media.discordapp.net/attachments/906874002579005491/915251132513800192/6tZ2i1K_d.webp it's this one it's a same u have to drag item just the design
