### ISSUE TITLE
Weapon draw

### ISSUE THREAD

**Issue by whiskeythrottle718** [dojwun/qb-inventory#17]
Hi, when drawing a weapon it pulls from the back, even if we use a weapon that has been put into the small resources weapdraw it still continues to draw from the back as a LEO with a duty belt rather that from the hip where it is supposed to

**Comment by dojwun** [comment]
ok thanks, i can add a config to disable the weapon draw in the inventory , i wasnt aware the was an existing weapon draw, i dont use qb-smallresources

**Comment by dojwun** [comment]
ive added the config, if there is anything i can help you with feel free to contact me on discord

**Comment by whiskeythrottle718** [comment]
Thank you so much!!

**Comment by dojwun** [comment]
not a problem
