### ISSUE TITLE
blur not fading out after closing the inventory and error

### ISSUE THREAD

**Issue by BlacknGoldy** [dojwun/qb-inventory#2]
Hi 
thank you for your sharing i was looking for that inventory :)
i attached picture https://imgur.com/BTPhFi9 for the error.
after i'm closing my inventory blur is still on my screen and cant move and when i click on the icon beside the i(information) im getting blur screen too!

**Comment by KIK02004** [comment]
If you changed the name of the inventory folder, you have to change the JavaScript file.

**Comment by BlacknGoldy** [comment]
i just removed -main after qb-inventory. so u mean i shouldn't remove the -main ?

**Comment by dojwun** [comment]
ive had a problem with the "Mixed Content Error" when i try to convert the __resource.lua to fxmanifest.lua, thats why i keep the __resource.lua, but you can try and use the fxmanifest.lua version and see if it works for you @BlacknGoldy

**Comment by sekem1000** [comment]
> O can help you tomorrow, so... Whats your discord name and tag?

brother i am having same problem can i get the fix?

**Comment by ch0sguy** [comment]
This repo is no longer being supported, sadly; you should most likely just find another inventory script if you cannot get a fix.
