### ISSUE TITLE
Weapon loading error!

### ISSUE THREAD

**Issue by hoangducdt** [dojwun/qb-inventory#7]
i use new qb-core, inventory has problem with weapon reloading, when i reload, ammo is not loaded! i use both your qb-inventory and qb-weapons, if using original  qb-inventory and original qb-weapons or aj-inventory this error does not appear

**Comment by dojwun** [comment]
inventory and weapons are a work in progress, haven't had much time to finish them, so there might be errors for the time being unless you fix them yourself
